__title__ = 'responsecodes'
__description__='Hypertext Transfer Protocol (HTTP) response status codes for humans'
__url__ = 'https://github.com/iamkamleshrangi/httpcodes'
__version__ = '0.0.1'
__author__ = 'Kamlesh Kumar Rangi'
__author_email__ = 'iamkamleshrangi@gmail.com'
__license__ = 'GPL v3'
__copyright__ = 'Copyright 2023 Kamlesh Kumar Rangi'
